name: "Terraform"

#with three different triggers
#push to the main branch
#is issue the release : tag a new release
#pull request : to go through and run terratest testing script to validate the configuration working as expected
on:
  push:
    branches:
      - main
  release:
    types: [published]
  pull_request:

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
    defaults:
      run:
        working-directory: managingMultipleEnvironment/file-structure/staging
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      #checking out the code base

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8
          terraform_wrapper: false
      #public github action step from hashicorp, that will setup terraform within the repo and use a specific version

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
      #format correctly

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        if: github.event_name  == 'pull_request'
        # Route 53 zone must already exist for this to suceed!
        run: terraform plan -var "database_password=${{ secrets.DATABASE_PASSWORD }}" -no-color
        continue-on-error: true

      - uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = '#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\'

            <details><summary>Show Plan</summary>

            \'\'\'${process.env.PLAN}\'\'\'

            </details>

            *Pusher: @${{ github.actor }}, Action: \'${{ github.event_name }}\'*';

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - uses: actions/setup-go@v5
        with:
          go-version: '1.27'

      - name: Terratest Execution
        if: github.event_name == 'pull_request'
        working-directory: testing/tests/terratest
        run: |
          go test . -v timeout -10m

      - name: Check tag
        id: check-tag
        run: |
          if [[ ${{ github.ref }} =~ ^refs\/tags\/v[0-9]+\.[0-9]+$ ]]; then
          echo "environment=production" >> "$GITHUB_OUTPUT"
          elif [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
          echo "environment=staging" >> "$GITHUB_OUTPUT"
          else
          echo "environment=unknown" >> "$GITHUB_OUTPUT"
          fi

      - name: Terraform Apply Global
        if: github.event_name == 'push' || github.event_name == 'release'
        working-directory: managingMultipleEnvironment/file-structure/global
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Terraform Apply Stagging
        if: steps.check-tag.outputs.environment == 'staging' && github.event_name == 'push'
        run: terraform apply -var database_password=${{secrets.DATABASE_PASSWORD}} -auto-approve

      - name: Terraform Apply Production
        if: steps.check-tag.outputs.environment == 'production' && github.event_name == 'release'
        working-directory: managingMultipleEnvironment/file-structure/production
        run: |
          terraform init
          terraform apply -var database_password=${{secrets.DATABASE_PASSWORD}} -auto-approve